#!/usr/bin/env bash
# Script that displays numbers from 1 to 20 and: with breaks in 4, 9, 17 using+ the while loop
i=1
while [ $i -le 20 ]; do
echo $i
case $i in
    4)
        echo bad luck from China
        ;;
    9)
echo bad luck from Japan
;;
    17)
echo bad luck from Italy
esac
((i++))
done
