#!/usr/bin/env bash
#Displays To infinity and beyond with a sleep 2 iteration
#Highlander? More like Homelander
trap 'echo "I am invincible!!!"' 15
while true; do
    echo "to infinity and beyond"
    sleep 2
done
